create table if not exists public.scan_records (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  date_iso text not null,
  time_label text not null,
  person text not null,
  result text not null,
  notice text not null,
  status text not null check (status in ('safe', 'warn', 'danger')),
  risk text not null check (risk in ('low', 'medium', 'high')),
  score integer not null default 0 check (score >= 0 and score <= 100),
  allergen_hit boolean not null default false,
  image_data text,
  summary text
);

alter table public.scan_records
  add column if not exists image_data text;

create index if not exists scan_records_created_at_idx
  on public.scan_records (created_at desc);

create index if not exists scan_records_date_iso_idx
  on public.scan_records (date_iso);

create table if not exists public.allergy_profiles (
  id bigint generated by default as identity primary key,
  profile_id text not null unique,
  name text not null,
  allergens jsonb not null default '[]'::jsonb,
  sensitivity text not null default 'normal' check (sensitivity in ('normal', 'high')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists allergy_profiles_updated_at_idx
  on public.allergy_profiles (updated_at desc);

alter table public.allergy_profiles enable row level security;

-- 本项目通过 Next.js 服务端 API 使用 SUPABASE_SERVICE_ROLE_KEY 访问数据库。
-- 不需要在浏览器暴露 Supabase 密钥，也不需要给 anon 用户开放表权限。
alter table public.scan_records enable row level security;
